CREATE TABLE PRODUTO(
EAN INT PRIMARY KEY NOT NULL IDENTITY(1,1),
DESCRICAO VARCHAR(100),
MARCA VARCHAR(50),
BU VARCHAR(50),
CATEGORIA VARCHAR(50),
PPA VARCHAR(50));

CREATE TABLE CLIENTE(
ID_CLIENTE INT PRIMARY KEY NOT NULL IDENTITY(1,1),
NOME_CLIENTE CHAR(30),
CANAL CHAR(30));

CREATE TABLE CALENDARIO(
ID_TEMPO INT PRIMARY KEY NOT NULL IDENTITY(1,1),
"DATA" DATE,
ANO INT,
MES INT,
NOME_MES VARCHAR(15));

CREATE TABLE SELLOUT(
ID_SELLOUT INT PRIMARY KEY NOT NULL IDENTITY(1,1),
ID_TEMPO INT NOT NULL,
ID_CLIENTE INT NOT NULL,
EAN INT NOT NULL,
SELLOUT_UND INT,
SELLOUT_VALOR DECIMAL(10,2),

CONSTRAINT FK_SELLOUT_TEMPO FOREIGN KEY(ID_TEMPO)
REFERENCES CALENDARIO(ID_TEMPO),

CONSTRAINT FK_SELLOUT_CLIENTE FOREIGN KEY(ID_CLIENTE)
REFERENCES CLIENTE(ID_CLIENTE),

CONSTRAINT FK_SELLOUT_EAN FOREIGN KEY(EAN)
REFERENCES PRODUTO(EAN));

SELECT*FROM CALENDARIO